[package]
name = "xenna"
version = "0.1.0"
edition = "2021"

[dependencies]
encoding_rs = "0.8"
memchr = "2"

[dev-dependencies]
divan = "0.1"
quick-xml = "0.36"
xml = "0.8"

[[bench]]
name = "macrobenches"
harness = false
